// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kxqekqbizrxotlqljcpr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imt4cWVrcWJpenJ4b3RscWxqY3ByIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY5Nzg4NjksImV4cCI6MjA2MjU1NDg2OX0.oRkMvwd-47iZs-soklrMXdYJaFIdiP1fUieRFjDBiPA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);